name: mac
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Setting the environment up.
      env:
        NGROK_AUTH_TOKEN: ${{2Onx190N1W5H6WGPmxw2hwArBg0_5Pbg1K1A6aafoytbibfJB }}
        VNC_USER_PASSWORD: ${{ 123456789 }}
        VNC_PASSWORD: ${{ 123456789 }}
      run: source configure.sh "123456789" "123456789" "2Onx190N1W5H6WGPmxw2hwArBg0_5Pbg1K1A6aafoytbibfJB"
    - name: ngrok is now listening to VNC connections on...
      run: curl --silent http://127.0.0.1:4040/api/tunnels | jq '.tunnels[0].public_url'
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v2
